// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXanHl0yBp8X9YUCwzvhGBRx4ej3ltox0',
    appId: '1:483110935745:web:53f1b456a90d6ab4358840',
    messagingSenderId: '483110935745',
    projectId: 'login2-pro',
    authDomain: 'login2-pro.firebaseapp.com',
    storageBucket: 'login2-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBATUtql4ZBTi4FfwDCD1iLAXER8ev0EsE',
    appId: '1:483110935745:android:a7208f0ee57894b8358840',
    messagingSenderId: '483110935745',
    projectId: 'login2-pro',
    storageBucket: 'login2-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8R9_wmKiynuU7FJqfcKMna1K6xAP8D3c',
    appId: '1:483110935745:ios:605fe7e2a453798c358840',
    messagingSenderId: '483110935745',
    projectId: 'login2-pro',
    storageBucket: 'login2-pro.firebasestorage.app',
    iosBundleId: 'com.example.kdcChittyMainnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8R9_wmKiynuU7FJqfcKMna1K6xAP8D3c',
    appId: '1:483110935745:ios:605fe7e2a453798c358840',
    messagingSenderId: '483110935745',
    projectId: 'login2-pro',
    storageBucket: 'login2-pro.firebasestorage.app',
    iosBundleId: 'com.example.kdcChittyMainnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXanHl0yBp8X9YUCwzvhGBRx4ej3ltox0',
    appId: '1:483110935745:web:15569bacdcb4d9c9358840',
    messagingSenderId: '483110935745',
    projectId: 'login2-pro',
    authDomain: 'login2-pro.firebaseapp.com',
    storageBucket: 'login2-pro.firebasestorage.app',
  );
}
